version: "3.0"
services:
  api:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    devices:
      - "/dev/spidev0.0:/dev/spidev0.0"
    networks:
      - default